// <auto-generated />
namespace Andino_Cristian_LPPA_Parcial1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Afiliados_EmailCUIT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Afiliados_EmailCUIT));
        
        string IMigrationMetadata.Id
        {
            get { return "202105312334351_Afiliados_EmailCUIT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
